apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: db
  labels:
    id: C0929653
    app: db
    env: dev
data:
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db
  labels:
    id: C0929653
    app: db
    env: dev
type: Opaque
data:
  MYSQL_PASSWORD: "d29yZHByZXNz"
  MYSQL_ROOT_PASSWORD: "c29tZXdvcmRwcmVzcw=="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: db
  labels:
    id: C0929653
    app: db
    env: dev
spec:
  selector:
    matchLabels:
      id: C0929653
  replicas: 3
  template:
    metadata:
      labels:
        app: db
        id: C0929653
        env: dev
    spec:
      containers:
      - name: db-container
        image: mariadb:10.6.4-focal
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-configmap
          - secretRef:
              name: db-secret

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db
  labels:
    version: v1
    id: C0929653
    app: db
    env: dev
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    id: C0929653

---
